### ISSUE TITLE
Change the question and answers

### ISSUE THREAD

**Issue by abieber1408** [abieber1408/capstone-project#2]
## Title
Add a button to change Question and possible answers.

## Value proposition

As an <actor>user
I want <feature>to list another question an its two possible answers
So that <benefit>I can change the question and answers per button click. 

## Description

- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria

- [x] If click Change question and answers.

## Tasks

- [x] Create a button. 
- 

![Image](https://user-images.githubusercontent.com/110246640/229459724-8608d863-a7e6-42a2-98df-492216f5313c.svg)

**Comment by PReichetanz** [comment]
Hi Anita,

a really good start for your user story! 🎉

💬 Let's discuss some issues which came to my mind while reading:

## General
Please move the image below the "Description" headline.

## Description
- What happens if I click on the button with the left arrow or the home symbol? Is there a page where they link to? Either add a wireframe to show this or describe it under the acceptance criteria.

## Acceptance Criteria
- I don't completely understand this: Where does the user click to get a new question?

## Tasks

**Comment by abieber1408** [comment]
By click on Button in Blue you get another question if you choose so.

The button with arrow symbol is not part of these story. I should not have put it here.

It will be on another  Wireframe

**Comment by PReichetanz** [comment]
You could add as another task to add more question to your dummy data, but that's up to you.

**Comment by abieber1408** [comment]
Could be. Thank you for your comments.
I will really keep it very simply at the beginning of the project.
